powsybl/powsybl-balances-adjustment

pom.xml, src/main/java/com/powsybl/balances_adjustment/util/VoltageLevelsArea.java
N/A
Release
powsybl-balances-adjustment's version is v1.0.0-SNAPSHOT. We also use powsybl-parent v3.
powsybl-balances-adjustment's version is v1.1.0-SNAPSHOT
(if any of the …
=> Prepare release v1.0.0

pom.xml, src/test/java/com/powsybl/balances_adjustment/balance_computation/json_parameters/JsonBalanceComputationParametersTest.java, src/test/java/com/powsybl/balances_adjustment/util/NetworkTestFactory.java, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
No
Update PowSyBl dependencies
=> Update powsybl-core and powsybl-open-loadflow dependencies

pom.xml
=> Release v1.1.0

pom.xml, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
=> Release v1.2.0

pom.xml, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
Signed-off-by: Sebastien Murgey <sebastien.murgey@rte-france.com>
=> Update powsybl dependencies version

pom.xml
=> Upgrade PowSyBl dependencies

pom.xml, src/test/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationImplDcTest.java, src/test/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationSimpleDcTest.java, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
Dependency update
Adapt test code to powsybl-core 3.8.0 changes.
=> Update powsybl-core and powsybl-open-loadflow

src/main/java/com/powsybl/balances_adjustment/data_exchange/DataExchanges.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/DataExchangesConstants.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/DataExchangesXml.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardBusinessType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardCodingSchemeType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardCurveType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardMessageType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardProcessType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardReasonCodeType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardRoleType.java, src/main/java/com/powsybl/balances_adjustment/data_exchange/StandardStatusType.java, src/test/java/com/powsybl/balances_adjustment/data_exchange/CgmaExchangesTest.java, src/test/java/com/powsybl/balances_adjustment/data_exchange/PevfExchangesTest.java, src/test/resources/testCGMAMarketDocument_2-0.xml
No
Feature
CGMA file cannot be parsed by PEVF xml parser
CGMA file can be parsed by PEVF xml parser renamed to DataExchangesXml
(if any of the questions/checkboxes don't apply, …
=> Add CGMA support to PEVF XML parser

pom.xml, src/test/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationImplDcTest.java, src/test/java/com/powsybl/balances_adjustment/balance_computation/json_parameters/JsonBalanceComputationParametersTest.java, src/test/java/com/powsybl/balances_adjustment/util/VoltageLevelsAreaTest.java
=> Upgrade powsybl version

pom.xml
=> Release v1.3.0

pom.xml
Signed-off-by: RALAMBOTIANA MIORA <miora.ralambotiana@rte-france.com>
Bump versions of powsybl dependencies: Bump core and olf versions respectively to 4.1.1 and 0.10.1
=> Bump core and olf versions respectively to 4.1.1 and 0.10.1

pom.xml, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
Signed-off-by: Anne Tilloy <anne.tilloy@rte-france.com>
=> Bump to 4.2.0-RC1

pom.xml
Prepare next release 1.7.0-SNAPSHOT
=> Prepare 1.6.0

pom.xml, src/main/java/com/powsybl/balances_adjustment/util/CountryArea.java, src/test/java/com/powsybl/balances_adjustment/util/CountryAreaTest.java
No
Bump powsybl-core to 4.4.0, together with powsybl-open-loadflow 0.13.0
=> Bump powsybl-core to 4.4.0

pom.xml
**Please check if the PR fulfills these requirements**
**Does this PR already have an issue describing the problem ?**
No
Version update
1.7.0-SNAPSHOT version
1.7.0 then 1.8.0-SNAPSHOT
**Does this PR introduce a breaking change or deprecate an API?**
No
Do not squash the commits
=> Release v1.7.0

src/test/java/com/powsybl/balances_adjustment/balance_computation/json_parameters/JsonBalanceComputationParametersTest.java
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
=> Fix Sonar issues

pom.xml, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
Prepare release 1.9.0
Do not squash commits
=> Prepare release 1.9

pom.xml
No
Prepare release 1.10.0
**DO NOT SQUASH COMMITS**
=> Prepare release 1.10.0

pom.xml, src/test/resources/balanceComputationParameters.json, src/test/resources/balanceComputationParametersWithExtension.json
No
Prepare release 1.12.0
Do no squash commits
=> Prepare 1.12.0

.github/workflows/maven.yml, pom.xml, src/main/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationArea.java, src/main/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationImpl.java, src/main/java/com/powsybl/balances_adjustment/util/NetworkAreaUtil.java, src/test/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationImplDcTest.java, src/test/java/com/powsybl/balances_adjustment/balance_computation/BalanceComputationSimpleDcTest.java, src/test/java/com/powsybl/balances_adjustment/util/NetworkAreaUtilTest.java
No
Bump core and olf to prepare new release
=> Bump core to 4.9.0 and olf to 0.21.0

pom.xml, src/test/java/com/powsybl/balances_adjustment/balance_computation/json_parameters/JsonBalanceComputationParametersTest.java
=> updated powsybl to 4.10.0 and OLF to 0.23.1

pom.xml
=> bumped powsybl to 4.10.1

pom.xml
=> Release1.14.0
